name: hive_service
description: My Hive Service package
version: 0.0.1
# publish_to: none
homepage: https://github.com/Eldar2021/hive_service

environment:
  sdk: ">=2.17.0 <3.0.0"

dev_dependencies:
  mocktail: ^0.3.0
  test: ^1.19.2
  very_good_analysis: ^3.0.1
dependencies: {hive: ^2.2.3}
